defaults: &defaults
  host: "barreleye.redistogo.com"
  password: "537f90af7561b140f024c6c76ed4e64f"
  port: 9999
  

development:
  <<: *defaults

test:
  <<: *defaults 
  db: 1

staging:
  <<: *defaults

production:
  <<: *defaults
