defaults: &defaults
  host: "barreleye.redistogo.com"
  password: "5d3778bf00753ad1003b3fa71983b43a"
  port: 10024

development:
  <<: *defaults

test:
  <<: *defaults 
  db: 1

staging:
  <<: *defaults

production:
  <<: *defaults
